{
 "title": "Dify Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Apps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "dify", "rawSql": "SELECT count(1) FROM apps" }
   ]
  },
  {
   "title": "Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "dify", "rawSql": "SELECT count(1) FROM messages" }
   ]
  },
  {
   "title": "Conversations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dify",
     "rawSql": "SELECT count(1) FROM conversations"
    }
   ]
  },
  {
   "title": "Tenants",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "dify", "rawSql": "SELECT count(1) FROM tenants" }
   ]
  },
  {
   "title": "Accounts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "dify", "rawSql": "SELECT count(1) FROM accounts" }
   ]
  },
  {
   "title": "Datasets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "dify", "rawSql": "SELECT count(1) FROM datasets" }
   ]
  },
  { "title": "Apps Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Apps in total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "dify", "rawSql": "SELECT count(1) FROM apps" }
   ]
  },
  {
   "title": "Apps by mode",
   "type": "stat",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dify",
     "rawSql": "SELECT \n  case mode\n    when 'advanced-chat' then 'Chatflow'\n    when 'workflow' then 'Workflow'\n    when 'agent-chat' then 'Agent'\n    when 'chat' then 'Chatbot'\n  end AS Mode,\n  COUNT(id) AS COUNT\nFROM apps\nGROUP BY mode"
    }
   ]
  },
  { "title": "Messages Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Messages in total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "dify", "rawSql": "SELECT count(1) FROM messages" }
   ]
  },
  {
   "title": "Top 10 Apps With Most Messages",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 16 },
   "targets": [
    {
     "dataset": "dify",
     "rawSql": "select apps.name            as app_name,\n       apps.id              as app_id,\n       message_counts.count as message_count\nfrom (SELECT COUNT(1) AS count,\n             app_id\n      FROM messages\n      GROUP BY app_id\n      order by count desc\n      limit 10) as message_counts\n         JOIN apps on message_counts.app_id = apps.id\norder by message_counts.count desc;\n"
    }
   ]
  },
  {
   "title": "Messages Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "dataset": "dify",
     "rawSql": "SELECT $__timeGroup(created_at,$__interval,0), COUNT(1) FROM messages WHERE $__timeFilter(created_at) GROUP BY $__timeGroup(created_at, $__interval, 0) ORDER BY $__timeGroup(created_at, $__interval, 0) "
    }
   ]
  },
  { "title": "Tenants title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Tenaunts in total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "dify", "rawSql": "SELECT count(1) FROM tenants" }
   ]
  },
  {
   "title": "Accounts by Tenants",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dify",
     "rawSql": "select\n    name as tenant_name,\n    count(1) as count\nfrom tenants\ngroup by id\norder by tenants desc"
    }
   ]
  }
 ]
}